#!/usr/bin/env python3
"""Build resources/map-data/sponsors.js: seed sponsors + per-route nearby locations (PRD-revenue.md).

Seed sponsors show on every route view; their location pins show only for
locations within NEAR_M of the selected route's geometry.
"""
import json
import math
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
NEAR_M = 150   # a location pins on a route only within this many meters of the LINE
MLON = 111320 * math.cos(math.radians(18.462)); MLAT = 110570


def seg_dist(px, py, ax, ay, bx, by):
    """meters from point (px,py) to segment a-b (all in projected meters)."""
    dx, dy = bx - ax, by - ay
    if dx == 0 and dy == 0:
        return math.hypot(px - ax, py - ay)
    t = max(0.0, min(1.0, ((px - ax) * dx + (py - ay) * dy) / (dx * dx + dy * dy)))
    return math.hypot(px - (ax + t * dx), py - (ay + t * dy))


def route_dist(px, py, parts):
    """min distance from a point to the route line (measured to segments, not vertices)."""
    best = float("inf")
    for pts in parts:
        if len(pts) == 1:
            best = min(best, math.hypot(px - pts[0][0], py - pts[0][1]))
        for i in range(len(pts) - 1):
            d = seg_dist(px, py, pts[i][0], pts[i][1], pts[i + 1][0], pts[i + 1][1])
            if d < best:
                best = d
    return best

SPONSORS = {
    "oxxo": {
        "name": "OXXO",
        "type": "Tiendas de conveniencia",   # Spanish category — drives the map's sponsor-type filter
        "logo": "patrocinadores/oxxo.png",
        "logo2x": "patrocinadores/oxxo@2x.png",
        "seed": True,  # placeholder per PRD-revenue §3 — replaced by first paying sponsor
        "locations_file": ROOT / "resources" / "data" / "sponsors" / "oxxo_locations.json",
    },
    "3b": {
        "name": "3B",
        "type": "Abarrotes",
        "logo": "patrocinadores/3b.png",      # tiendas3b.com brand mark, circular-masked
        "logo2x": "patrocinadores/3b@2x.png",
        "seed": True,      # free destination-pin seed (Tiendas 3B), like OXXO
        "locations_file": ROOT / "resources" / "data" / "sponsors" / "3b_locations.json",
    },
}


def main():
    routes = json.loads((ROOT / "resources" / "map-data" / "routes.js").read_text().split("const ROUTES = ", 1)[1].rstrip().rstrip(";"))

    # each route -> list of parts, each part a list of projected (x,y) vertices, so
    # distance is measured to the SEGMENTS (the line itself), not just the vertices.
    flat = {}
    for f in routes["features"]:
        flat[f["properties"]["id"]] = [[(c[0] * MLON, c[1] * MLAT) for c in part]
                                       for part in f["geometry"]["coordinates"]]

    out = {"sponsors": {}, "by_route": {}}
    for sid, s in SPONSORS.items():
        locs = json.loads(s["locations_file"].read_text())["locations"]
        # the sponsor carries its FULL location list (its directory "homepage" needs
        # them all); route pins reference a location by its index so nothing is duped.
        clean = [{"lon": round(l["lon"], 6), "lat": round(l["lat"], 6),
                  "addr": l.get("addr") or None, "hours": l.get("hours") or None,
                  "phone": l.get("phone") or None} for l in locs]
        out["sponsors"][sid] = {"name": s["name"], "type": s.get("type") or None,
                                "logo": s["logo"], "logo2x": s["logo2x"], "seed": s["seed"],
                                "locations": clean}
        for rid, parts in flat.items():
            near = []
            for idx, loc in enumerate(locs):
                lx, ly = loc["lon"] * MLON, loc["lat"] * MLAT
                if route_dist(lx, ly, parts) <= NEAR_M:
                    near.append([round(loc["lon"], 6), round(loc["lat"], 6), idx])
            if near:
                out["by_route"].setdefault(rid, {})[sid] = near

    js = "// generated by scripts/12_build_sponsors.py — do not edit\nconst SPONSORS = " + \
         json.dumps(out, ensure_ascii=False, separators=(",", ":")) + ";\n"
    (ROOT / "resources" / "map-data" / "sponsors.js").write_text(js, encoding="utf-8")
    n_routes = len(out["by_route"])
    n_pins = sum(len(v) for r in out["by_route"].values() for v in r.values())
    print(f"resources/map-data/sponsors.js: {len(out['sponsors'])} sponsor(s), pins on {n_routes} routes ({n_pins} route-pin pairs)")


if __name__ == "__main__":
    main()
