#!/usr/bin/env python3
"""Streets + intersections layer — makes "reforma nte y 16 ote" resolvable.

Tehuacán is a numbered grid; the single most natural way locals name a place
is the esquina ("Reforma Norte y 16 Oriente"). Generic geocoders parse this
poorly; OSM has it exactly: ways share a node where streets cross. This script
pulls every named street in the service area, finds nodes shared by ways with
different names (= intersections), and emits resources/map-data/calles.js:

  const CALLES = {streets: [{n, c}], cruces: [{n, c}]}

The app lazy-loads it as a search tier (token matching + abbreviation
expansion client-side). Refreshed by the weekly agent.
"""
import importlib
import json
import sys
import time
import urllib.parse
import urllib.request
from collections import defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
build_pois = importlib.import_module("15_build_pois")

ROOT = Path(__file__).resolve().parents[2]
BUFFER_DEG = 0.03
ENDPOINTS = [
    "https://overpass.kumi.systems/api/interpreter",
    "https://overpass-api.de/api/interpreter",
]
UA = "mitehuacan.mx streets refresh (github.com/augmentedmike/mitehuacan.mx)"
HIGHWAYS = "primary|secondary|tertiary|residential|living_street|unclassified|trunk|pedestrian"


def overpass(q):
    data = ("data=" + urllib.parse.quote(q)).encode()
    last = None
    for url in ENDPOINTS:
        for _ in range(2):
            try:
                req = urllib.request.Request(url, data=data, headers={"User-Agent": UA})
                with urllib.request.urlopen(req, timeout=180) as r:
                    return json.loads(r.read())
            except Exception as e:  # noqa: BLE001
                last = e
                time.sleep(5)
    raise RuntimeError(f"overpass failed: {last}")


def main():
    routes = build_pois.load_routes()
    lons, lats = [], []
    for f in routes["features"]:
        for part in f["geometry"]["coordinates"]:
            for lon, lat in part:
                lons.append(lon)
                lats.append(lat)
    s, w = min(lats) - BUFFER_DEG, min(lons) - BUFFER_DEG
    n, e = max(lats) + BUFFER_DEG, max(lons) + BUFFER_DEG

    raw = overpass(
        f'[out:json][timeout:150];way["highway"~"^({HIGHWAYS})$"]["name"]({s},{w},{n},{e});out body;>;out skel qt;')

    coords = {}
    for el in raw["elements"]:
        if el["type"] == "node":
            coords[el["id"]] = (el["lon"], el["lat"])

    node_names = defaultdict(set)     # node id -> street names crossing it
    street_pts = defaultdict(list)    # street name -> its points
    for el in raw["elements"]:
        if el["type"] != "way":
            continue
        name = " ".join(el["tags"]["name"].split())[:50]
        for nid in el["nodes"]:
            node_names[nid].add(name)
            if nid in coords:
                street_pts[name].append(coords[nid])

    # intersections = nodes shared by >=2 distinct street names
    cruces, seen = [], set()
    for nid, names in node_names.items():
        if len(names) < 2 or nid not in coords:
            continue
        lon, lat = coords[nid]
        label = " y ".join(sorted(names)[:3])
        key = (label, round(lon, 3), round(lat, 3))   # same pair within ~100m: keep one
        if key in seen:
            continue
        seen.add(key)
        cruces.append({"n": label, "c": [round(lon, 6), round(lat, 6)]})

    streets = []
    for name, pts in street_pts.items():
        mid = pts[len(pts) // 2]
        streets.append({"n": name, "c": [round(mid[0], 6), round(mid[1], 6)]})
    streets.sort(key=lambda x: x["n"].lower())
    cruces.sort(key=lambda x: x["n"].lower())

    out = ROOT / "resources" / "map-data" / "calles.js"
    out.write_text(
        "// generated by src/scripts/20_build_streets.py from OSM (ODbL) — do not edit.\n"
        "// SEARCH data only: streets + esquinas so 'reforma nte y 16 ote' resolves.\n"
        "const CALLES = " + json.dumps({"streets": streets, "cruces": cruces},
                                         ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8")
    kb = out.stat().st_size // 1024
    print(f"calles: {len(streets)} streets, {len(cruces)} intersections ({kb} KB)")


if __name__ == "__main__":
    main()
