#!/usr/bin/env python3
"""Publish the discovery harvest into the app's search index.

Reads the cross-source unified store (resources/discovery/unified.db) and emits
resources/map-data/discovery.js — the agent/crowdsourced businesses that have
coordinates, in the same shape the app searches (like denue.js). These are
net-new vs OSM/DENUE (deduped at scrape time), so publishing them makes places
like the ones our agents found searchable and routable.

  python3 src/scripts/23_publish_discovery.py

Only records WITH coordinates are published (searchable + mappable). No-coord
records (e.g. Instagram-only accounts) stay in the queue until a location is
added.
"""
import json
import sqlite3
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
DB = ROOT / "resources" / "discovery" / "unified.db"
OUT = ROOT / "resources" / "map-data" / "discovery.js"


def main():
    if not DB.exists():
        raise SystemExit(f"no unified store at {DB} — run discover/unify.py first")
    db = sqlite3.connect(DB)
    rows = db.execute(
        "SELECT name, lat, lon, category, address FROM places WHERE lat IS NOT NULL AND lon IS NOT NULL").fetchall()
    seen, places = set(), []
    for name, lat, lon, cat, address in rows:
        name = (name or "").strip()
        if len(name) < 3:
            continue
        key = (name.lower(), round(lat, 4), round(lon, 4))
        if key in seen:
            continue
        seen.add(key)
        kind = ((cat or "").split(",")[0].strip() or "negocio")
        rec = {"n": name[:80], "c": [round(lon, 6), round(lat, 6)], "k": kind}
        if address:
            rec["a"] = address[:100]        # street address for display
        places.append(rec)
    OUT.write_text(
        "// generated by scripts/23_publish_discovery.py from the discovery unified store.\n"
        "// agent/crowdsourced businesses (net-new vs OSM/DENUE). SEARCH data only, never pins.\n"
        "const DISCOVERY = " + json.dumps({"places": places}, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8")
    kb = OUT.stat().st_size // 1024
    print(f"discovery: {len(places)} places -> resources/map-data/discovery.js ({kb} KB)")


if __name__ == "__main__":
    main()
