#!/usr/bin/env python3
"""Publish the collected events into the app's calendar feed.

Reads EVERY event lifecycle store (resources/discovery/*_events.db — fb_events,
gov_events, and any future source), normalizes each record with events_common
(Spanish date -> ISO, venue -> coords, title -> category), drops past/stale and
junk rows, DEDUPES the same fiesta seen across sources, and emits
resources/map-data/events.js:

  const EVENTS = {"events":[{t,d,tm,v,c:[lon,lat],k,town,src:[...],u,x}]}

  t=title d=ISO-date tm=HH:MM v=venue/town k=category town src=sources
  u=link x=1 when the date is approximate ("por confirmar", e.g. derived fiestas)

  python3 src/scripts/25_publish_events.py

Only current+upcoming events are published (past ones stay in the stores as
history). Same stores => same file (deterministic).
"""
import json
import sqlite3
from datetime import date, timedelta
from pathlib import Path

import sys
sys.path.insert(0, str(Path(__file__).resolve().parent / "discover"))
from events_common import (  # noqa: E402
    parse_date_es, parse_time_es, categorize, geocode_event, town_of,
    load_cruces, TOWN_CENTER)

ROOT = Path(__file__).resolve().parents[2]
DISC = ROOT / "resources" / "discovery"
OUT = ROOT / "resources" / "map-data" / "events.js"

TODAY = date.today()
HORIZON = TODAY + timedelta(days=400)
_TOWN_NORMS = {t.lower() for t in TOWN_CENTER}


def _norm(s):
    return "".join(c for c in s.lower() if c.isalnum())


def _junk(title, town):
    t = title.strip()
    return len(t) < 5 or t.lower() in _TOWN_NORMS or _norm(t) == _norm(town)


def main():
    stores = sorted(DISC.glob("*_events.db"))
    if not stores:
        raise SystemExit(f"no *_events.db stores in {DISC}")
    cruces = load_cruces()
    merged = {}                      # dedup key -> event
    read = kept = 0
    for db_path in stores:
        db = sqlite3.connect(db_path)
        db.row_factory = sqlite3.Row
        rows = db.execute("SELECT * FROM records WHERE status IN ('candidate','approved')").fetchall()
        for r in rows:
            read += 1
            when = parse_date_es(r["subcat"] or "", TODAY)
            if not when or when < TODAY or when > HORIZON:
                continue
            title = (r["name"] or "").strip()
            town = r["where_"] or town_of(title) or "Tehuacán"
            if _junk(title, town):
                continue
            if r["lat"] is not None and r["lon"] is not None:
                c = [round(r["lon"], 6), round(r["lat"], 6)]
            else:
                c = geocode_event(town, town_of(town), cruces)
            ev = {
                "t": title[:90],
                "d": when.isoformat(),
                "tm": parse_time_es(r["subcat"] or ""),
                "v": town,
                "c": c,
                "k": categorize(title),
                "town": town,
                "src": [r["source"]],
                "u": r["url"] or "",
                "x": 1 if (r["handle"] == "approx") else 0,
            }
            key = (_norm(title)[:24], ev["d"], _norm(town))
            if key in merged:
                m = merged[key]
                if r["source"] not in m["src"]:
                    m["src"].append(r["source"])
                if not m["u"] and ev["u"]:
                    m["u"] = ev["u"]
                m["x"] = 1 if (m["x"] and ev["x"]) else 0   # confirmed by any real source
            else:
                merged[key] = ev
                kept += 1
        db.close()

    events = sorted(merged.values(), key=lambda e: (e["d"], e["tm"] or "99:99", e["t"]))
    OUT.write_text(
        "// generated by scripts/25_publish_events.py from the event lifecycle stores.\n"
        "// current+upcoming events for the calendar. x=1 => date por confirmar.\n"
        "const EVENTS = " + json.dumps({"events": events}, ensure_ascii=False, separators=(",", ":")) + ";\n",
        encoding="utf-8")
    kb = OUT.stat().st_size // 1024
    approx = sum(1 for e in events if e["x"])
    srcs = {s for e in events for s in e["src"]}
    print(f"events: read {read} store rows -> {len(events)} upcoming published "
          f"({approx} por confirmar) from {', '.join(sorted(srcs)) or 'no sources'} "
          f"-> resources/map-data/events.js ({kb} KB)")


if __name__ == "__main__":
    main()
